name: CI/CD-Deployment
  
on:
    workflow_dispatch:

jobs:
  Prod_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id      :  ${{ secrets.TN_AWS_ACCESS_KEY }}
          aws-secret-access-key  :  ${{ secrets.TN_AWS_SECRET_KEY }}
          aws-region             :  ${{ vars.AWS_REGION_NAME }}

      - name: Swap staging and production environments
        run: aws elasticbeanstalk swap-environment-cnames --source-environment-name ${{ vars.EB_ENVIRONMENT_NAME_GREEN }} --destination-environment-name ${{ vars.EB_ENVIRONMENT_NAME_BLUE }}
    
