name: CI/CD-Deployment

env:
    EB_APPLIACTION_NAME        :  "bpcalc-app"
    EB_ENVIRONMENT_NAME_QA     :  "bpcalc-app-qa-env"
    EB_ENVIRONMENT_NAME_BLUE   :  "bpcalc-app-blue-env"
    EB_ENVIRONMENT_NAME_GREEN  :  "bpcalc-app-green-env"
    AWS_REGION_NAME            :  "eu-west-1"
  
on:
    workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id      :  ${{ secrets.TN_AWS_ACCESS_KEY }}
          aws-secret-access-key  :  ${{ secrets.TN_AWS_SECRET_KEY }}
          aws-region             :  ${{ env.AWS_REGION_NAME }}

      - name: Swap staging and production environments
        run: aws elasticbeanstalk swap-environment-cnames --source-environment-name ${{ env.EB_ENVIRONMENT_NAME_GREEN }} --destination-environment-name ${{ env.EB_ENVIRONMENT_NAME_BLUE }}
    
