name: CI-CD-Pipeline-to-AWS-ElasticBEanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME  :  "tn-tud-csd-ca1-bpcalc-packages"
  EB_APPLIACTION_NAME        :  "bpcalc-app-qa"
  EB_ENVIRONMENT_NAME        :  "bpcalc-app-qa-env"
  DEPLOY_PACKAGE_NAME        :  "bpcala_app_${{ github.sha }}.zip"
  AWS_REGION_NAME            :   "eu-west-1"
  
on:
  push:
    branches:
      - main
jobs:
  bpcalc_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: Create ZIP deployment package
      run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*

    
