name: CI-CD-Pipeline-to-AWS-ElasticBEanstalk
env:
  QA_EB_PACKAGE_S3_BUCKET_NAME  :  "tn-tud-csd-ca1-bpcalc-packages"
  QA_EB_APPLIACTION_NAME        :  "bpcalc-app-qa"
  QA_EB_ENVIRONMENT_NAME        :  "bpcalc-app-qa-env"
  DEPLOY_PACKAGE_NAME           :  "bpcalc_app_${{ github.sha }}.zip"
  AWS_REGION_NAME               :  "eu-west-1"
  
on:
  push:
    branches:
      - main
jobs:
  QA_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id      :  ${{ secrets.TN_AWS_ACCESS_KEY }}
        aws-secret-access-key  :  ${{ secrets.TN_AWS_SECRET_KEY }}
        aws-region             :  ${{ env.AWS_REGION_NAME }}

    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.QA_EB_PACKAGE_S3_BUCKET_NAME }}/

    - name: Create new ElasticBEanstalk Application Version
      run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.QA_EB_APPLIACTION_NAME }} \
        --source-bundle S3Bucket="${{ env.QA_EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME}}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"

    - name: Deploy new Elastic Beanstalk Application Version
      run : aws elasticbeanstalk update-environment --environment-name ${{ env.QA_EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

    - name: Print Message for CD finish
      run : echo "Deployment completed successfully!"