name: Test_Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME  :  "tn-tud-csd-ca1-bpcalc-packages"
  EB_APPLIACTION_NAME        :  "bpcalc-app"
  EB_ENVIRONMENT_NAME_QA     :  "bpcalc-app-qa-env"
  EB_ENVIRONMENT_NAME_BLUE   :  "bpcalc-app-blue-env"
  EB_ENVIRONMENT_NAME_GREEN  :  "bpcalc-app-green-env"
  AWS_REGION_NAME            :  "eu-west-1"
  DEPLOY_PACKAGE_NAME        :  "deploy.zip"
  APP_VERSION                :  "Ver-${{ github.sha }}"
  
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  
jobs:
  CI_part:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      :  ${{ secrets.TN_AWS_ACCESS_KEY }}
          aws-secret-access-key  :  ${{ secrets.TN_AWS_SECRET_KEY }}
          aws-region             :  ${{ env.AWS_REGION_NAME }}

      - name: Get environment domain name
        run: DOMAIN=$(aws elasticbeanstalk describe-environments --environment-names ${{ env.EB_ENVIRONMENT_NAME_GREEN }} --query "Environments[0].CNAME" --output text >> $GITHUB_ENV
      
      - name: print domain name
        run: echo $DOMAIN

    # - name: Set Timestamp as env variable
    #   run: echo "NOW=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
          
    # - name: Set package name as env variable
    #   run: echo "DEPLOY_PACKAGE_NAME=bpcalc_app_$NOW.zip" >> $GITHUB_ENV
     
    # - name: Echo current date
    #   run: echo $DEPLOY_PACKAGE_NAME
      #run: echo $NOW + .zip # Gives "2022-12-11T01:42:20"
