name: Test_Pipeline
env:
  APP_VERSION                :  "Ver-${{ github.sha }}"
  EB_STAGING_ENV             :  ""
  
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  
jobs:
  CD_part_Testing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with: 
          target: "http://bpcalcqa.ntcyber.net"
          