name: Test_Pipeline
env:
  APP_VERSION                :  "Ver-${{ github.sha }}"
  QA_URL                     :  ""
  EB_STAGING_ENV             :  ""
  
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  
jobs:
  CD_part_Testing:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run JMeter performance test
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: tests/bpcalcqa-jmeter.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
      
      
      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: reports/
