name: Test_Pipeline
env:
  APP_VERSION                :  "Ver-${{ github.sha }}"
  QA_URL                     :  ""
  EB_STAGING_ENV             :  ""
  
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  
jobs:
  CD_part_Testing:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0

        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ vars.QA_URL }}
